export const APPLICATION_STATUSES = [
	"APPLIED",
	"UNDER_REVIEW",
	"SHORTLISTED_FOR_TEST",
	"TEST_SCHEDULED",
	"SHORTLISTED_FOR_INTERVIEW",
	"INTERVIEW_SCHEDULED",
	"SELECTED",
	"REJECTED",
	"WITHDRAWN",
	"SHORTLISTED",
	"NOT_APPLIED",
];
